import React from 'react';
import { StyleSheet } from 'react-native';
import { Fonts } from '@/constants/theme';

export const LIGHT_THEME = {
  scheme: 'light' as const,
  bg: '#F1F5F9',
  card: '#E2E8F0',
  cardBorder: '#CBD5E1',
  primary: '#EA580C',
  accent: '#EA580C',
  success: '#16A34A',
  warning: '#CA8A04',
  danger: '#DC2626',
  text: '#0F172A',
  textDim: '#475569',
  surface: '#E2E8F0',
  tabBarBg: 'rgba(241,245,249,0.95)',
  tabBarBorder: '#CBD5E1',
  blurTint: 'light' as const,
};

export const DARK_THEME = {
  scheme: 'dark' as const,
  bg: '#0F172A',
  card: '#1E293B',
  cardBorder: '#334155',
  primary: '#F97316',
  accent: '#F97316',
  success: '#22C55E',
  warning: '#F59E0B',
  danger: '#EF4444',
  text: '#F8FAFC',
  textDim: '#94A3B8',
  surface: '#1E293B',
  tabBarBg: 'rgba(15,23,42,0.95)',
  tabBarBorder: '#334155',
  blurTint: 'dark' as const,
};

export const ThemeContext = React.createContext({
  theme: LIGHT_THEME,
  statusBarStyle: 'dark' as 'light' | 'dark',
});

export const StylesContext = React.createContext<ReturnType<typeof createStyles> | null>(null);

export const useTheme = () => React.useContext(ThemeContext);
export const useStyles = () => {
  const ctx = React.useContext(StylesContext);
  return ctx || createStyles(LIGHT_THEME);
};

export const createStyles = (theme: typeof LIGHT_THEME) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.bg },
    appLayer: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
    onboardingLayer: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0 },
    screenContainer: { flex: 1, padding: 20, backgroundColor: theme.bg },
    onboardingWrap: { justifyContent: 'center', alignItems: 'center', padding: 24 },
    onboardingCard: { width: '100%', maxWidth: 360, backgroundColor: theme.card, borderRadius: 8, padding: 20, borderWidth: 1, borderColor: theme.cardBorder, alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 2 },
    onboardingIcon: { width: 56, height: 56, borderRadius: 8, backgroundColor: theme.surface, alignItems: 'center', justifyContent: 'center', marginBottom: 14, borderWidth: 1, borderColor: theme.cardBorder },
    onboardingTitle: { fontSize: 28, fontWeight: '700', color: theme.text, fontFamily: Fonts.sans },
    onboardingSub: { color: theme.textDim, marginTop: 4, marginBottom: 20, fontSize: 14 },
    onboardingList: { width: '100%', marginBottom: 12 },
    onboardingListGroup: { backgroundColor: theme.surface, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, overflow: 'hidden' },
    onboardingRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 16, gap: 12, minHeight: 72 },
    onboardingLogo: { width: 72, height: 72, alignItems: 'center', justifyContent: 'center' },
    onboardingLogoText: { color: theme.primary, fontSize: 14, fontWeight: '700' },
    onboardingRowTitle: { color: theme.text, fontWeight: '700', fontSize: 18, fontFamily: Fonts.sans },
    onboardingRowSub: { color: theme.textDim, fontSize: 14, marginTop: 4, fontFamily: Fonts.mono },
    onboardingDivider: { height: 1, backgroundColor: theme.cardBorder },
    onboardingInput: { width: '100%', textAlign: 'center', fontSize: 22 },
    onboardingBtn: { width: '100%', marginTop: 24 },
    onboardingDividerLine: { height: 1, backgroundColor: theme.cardBorder, width: '100%', marginTop: 16, marginBottom: 10 },
    addCarLink: { alignSelf: 'center', paddingVertical: 6 },
    addCarLinkText: { color: theme.primary, fontSize: 12, fontWeight: '700', letterSpacing: 0.6 },
    
    // Hero
    heroContainer: { backgroundColor: theme.card, margin: 16, padding: 16, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 12, shadowOffset: { width: 0, height: 8 }, elevation: 2 },
    heroLogo: { fontSize: 16, color: theme.primary, fontWeight: '600', letterSpacing: 0.6, textTransform: 'uppercase' },
    brandLogoWrap: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
    headerBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 0, paddingBottom: 6 },
    headerTitle: { color: theme.text, fontSize: 24, fontWeight: '700' },
    headerPill: { backgroundColor: theme.primary, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, flexDirection: 'row', alignItems: 'center', gap: 6 },
    headerPillText: { color: 'white', fontWeight: '600', fontSize: 14 },
    heroTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    heroNickname: { color: theme.textDim, fontStyle: 'italic', marginTop: 4 },
    heroBottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
    heroBrand: { color: theme.textDim, fontWeight: '700', letterSpacing: 0.6, textTransform: 'uppercase', fontSize: 14 },
    heroModel: { fontSize: 24, fontWeight: '800', color: theme.text, marginTop: -2, fontFamily: Fonts.sans },
    heroLinePlate: { color: theme.text, fontWeight: '700', fontSize: 18, letterSpacing: 1.4, fontFamily: Fonts.mono },
    heroStatus: { color: theme.textDim, fontSize: 14, marginTop: 6 },
    heroChangeText: { color: theme.primary, fontWeight: '600', fontSize: 14 },
    heroMetaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    heroMeta: { color: theme.textDim, fontSize: 14, fontWeight: '600' },
    heroMetaDot: { color: theme.textDim, paddingHorizontal: 6 },
    mileageRow: { marginTop: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.surface, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder },
    mileageLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    mileageText: { color: theme.text, fontWeight: '600', fontSize: 14 },

    // Sections
    section: { marginBottom: 24, paddingHorizontal: 20 },
    sectionTitle: { color: theme.textDim, fontSize: 14, fontWeight: '700', marginBottom: 12, letterSpacing: 0.4 },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
    projectHeroCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginBottom: 16 },
    projectHeroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
    projectHeroLabel: { color: theme.primary, fontWeight: '700', fontSize: 14, letterSpacing: 0.4, textTransform: 'uppercase' },
    projectHeroTitle: { color: theme.text, fontSize: 22, fontWeight: '700', marginTop: 4 },
    projectHeroMeta: { color: theme.textDim, fontSize: 14, marginTop: 4 },
    projectHeroDesc: { color: theme.text, marginTop: 10 },
    projectHeroActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
    projectStatusPill: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
    projectStatusPillText: { color: 'white', fontWeight: '700', fontSize: 14 },
    inlineCta: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10 },
    inlineCtaText: { color: theme.primary, fontWeight: '600' },
    nextGoalPill: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, paddingVertical: 8, paddingHorizontal: 10, borderRadius: 8, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.cardBorder },
    nextGoalText: { color: theme.text, fontWeight: '600', fontSize: 14, flex: 1 },
    statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 16 },
    statCard: { width: '48%', backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 14 },
    statLabel: { color: theme.textDim, fontSize: 14, fontWeight: '700' },
    statValue: { color: theme.text, fontSize: 18, fontWeight: '700', marginTop: 6, fontFamily: Fonts.mono },
    statSub: { color: theme.textDim, fontSize: 14, marginTop: 4 },
    budgetCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginBottom: 16 },
    budgetMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 },
    textButton: { paddingHorizontal: 8, paddingVertical: 4 },
    textButtonText: { color: theme.primary, fontWeight: '600', fontSize: 14 },
    projectCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginBottom: 20 },
    projectBadge: { color: theme.textDim, fontSize: 14, fontWeight: '700', letterSpacing: 0.4 },
    projectMeta: { color: theme.textDim, fontSize: 14 },
    projectStats: { color: theme.text, fontWeight: '600', marginTop: 4 },
    tagButton: { padding: 12, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
    projectListItem: { padding: 16, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: theme.card, marginBottom: 12 },
    projectRow: { flexDirection: 'row', alignItems: 'stretch' },
    projectStatusStrip: { width: 4, borderRadius: 8 },
    projectContent: { flex: 1, marginLeft: 12 },
    projectTopRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    projectTopMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    projectStarBtn: { padding: 4 },
    projectBottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 10 },
    tabBarRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, paddingBottom: 10 },
    tabPill: { flex: 1, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: theme.surface, alignItems: 'center' },
    tabPillText: { color: theme.text, fontWeight: '600', fontSize: 14 },
    sheetOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
    sheetContainer: { backgroundColor: theme.card, paddingTop: 12, paddingBottom: 16, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 16 },
    sheetHandle: { width: 40, height: 4, borderRadius: 8, backgroundColor: theme.cardBorder, alignSelf: 'center', marginBottom: 8 },
    sheetItem: { alignItems: 'center' },
    sheetPrimaryBtn: { backgroundColor: theme.primary, borderRadius: 8, paddingVertical: 12, marginBottom: 10 },
    sheetPrimaryText: { color: 'white', fontSize: 16, fontWeight: '700' },
    sheetDangerBtn: { backgroundColor: theme.surface, borderRadius: 8, paddingVertical: 12, borderWidth: 1, borderColor: theme.cardBorder },
    sheetDangerText: { color: theme.danger, fontSize: 16, fontWeight: '700' },
    projectPill: { marginTop: 8, alignSelf: 'flex-start', flexDirection: 'row', gap: 6, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: theme.surface, borderWidth: 1, borderColor: theme.cardBorder },
    chip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1 },
    quickActionRow: { flexDirection: 'row', gap: 12, marginBottom: 16 },
    emptyCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, gap: 8 },
    emptyInline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    emptyLink: { color: theme.primary, fontWeight: '600' },
    budgetBarWrap: { marginTop: 8, marginBottom: 8 },
    budgetBarTrack: { height: 6, borderRadius: 8, backgroundColor: theme.surface, overflow: 'hidden' },
    budgetBarFill: { height: 6, borderRadius: 8, backgroundColor: theme.primary },
    goalRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 12, marginBottom: 10 },
    goalRowDone: { backgroundColor: theme.surface, borderColor: 'rgba(50,215,75,0.4)' },
    goalCheck: { width: 28, alignItems: 'center', justifyContent: 'center' },
    goalCheckBox: { width: 20, height: 20, borderWidth: 2, borderColor: theme.cardBorder, borderRadius: 2, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.surface },
    goalCheckBoxDone: { backgroundColor: theme.primary, borderColor: theme.primary },
    goalContent: { flex: 1 },
    goalTitle: { color: theme.text, fontWeight: '600', fontSize: 15 },
    goalTitleDone: { color: theme.textDim, textDecorationLine: 'line-through' },
    goalMeta: { color: theme.textDim, fontSize: 14, marginTop: 2 },
    goalDelete: { padding: 6 },
    goalProgressRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10, gap: 10 },
    activeProjectCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginBottom: 16 },
    activeProjectLabel: { color: theme.primary, fontWeight: '700', fontSize: 14, letterSpacing: 0.4, textTransform: 'uppercase' },
    activeProjectTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    activeProjectActions: { flexDirection: 'row', gap: 12, marginTop: 14 },
    activeProjectGoal: { color: theme.text, fontWeight: '600', marginTop: 6 },
    activeProjectGoalEmpty: { color: theme.textDim, marginTop: 6 },
    fullscreenOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.9)', justifyContent: 'center', alignItems: 'center' },
    fullscreenHeader: { position: 'absolute', top: 40, left: 20, right: 20, flexDirection: 'row', justifyContent: 'space-between', zIndex: 2 },
    fullscreenImage: { width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center' },
    
    // Grid
    grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    specBox: { width: '31%', backgroundColor: theme.card, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, minHeight: 90 },
    specLabel: { color: theme.textDim, fontSize: 14, marginTop: 'auto' },
    specValue: { color: theme.text, fontWeight: '600', fontSize: 14, marginTop: 2 },

    // Tiles
    tileGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    infoTile: { width: '48%', backgroundColor: theme.card, padding: 14, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder },
    infoTileHeader: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 10 },
    infoTileLabel: { color: theme.textDim, fontSize: 14, fontWeight: '700' },
    infoTileValue: { color: theme.text, fontSize: 18, fontWeight: '700', fontFamily: Fonts.mono },
    infoTileSub: { color: theme.textDim, fontSize: 14, marginTop: 4 },

    // Alerts
    alertCard: { width: 140, backgroundColor: theme.card, marginRight: 12, padding: 16, borderRadius: 8, borderTopWidth: 4 },
    alertTitle: { color: theme.text, fontWeight: '600', fontSize: 14 },
    alertValue: { fontSize: 18, fontWeight: '700', marginVertical: 4 },
    alertSub: { color: theme.textDim, fontSize: 14 },

    // Logs
    logRow: { flexDirection: 'row', marginBottom: 20 },
    logTimelineLine: { width: 2, backgroundColor: theme.cardBorder, position: 'absolute', left: 15, top: 0, bottom: -20 },
    logIconParams: { width: 32, height: 32, borderRadius: 8, backgroundColor: theme.bg, borderWidth: 2, alignItems: 'center', justifyContent: 'center', zIndex: 2 },
    logContent: { flex: 1, marginLeft: 12, backgroundColor: theme.card, padding: 12, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder },
    logTitle: { color: theme.text, fontWeight: '600' },
    logDate: { color: theme.textDim, fontSize: 14, fontFamily: Fonts.mono },
    logNotes: { color: theme.textDim, fontSize: 14, marginVertical: 4 },
    logMeta: { color: theme.primary, fontSize: 14, fontWeight: '600' },
    logCost: { color: theme.danger, fontSize: 14, fontWeight: '600' },

    // Tab Bar
    tabBarContainer: { position: 'absolute', left: 0, right: 0, bottom: 0 },
    tabBar: { flex: 1, backgroundColor: theme.tabBarBg, borderTopWidth: 1, borderColor: theme.tabBarBorder },
    tabBarContent: { height: 49, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-evenly', paddingHorizontal: 12, paddingTop: 6 },
    tabBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', height: '100%' },
    tabLabel: { fontSize: 14, fontWeight: '500', marginTop: 2 },

    // Forms
    input: { backgroundColor: theme.card, color: theme.text, padding: 16, borderRadius: 8, marginBottom: 16, borderWidth: 1, borderColor: theme.cardBorder },
    inpLabel: { color: theme.textDim, fontSize: 14, fontWeight: '600', marginBottom: 8 },
    mainBtn: { backgroundColor: theme.primary, padding: 16, borderRadius: 8, alignItems: 'center', minHeight: 48 },
    primaryBtn: { backgroundColor: theme.primary, padding: 12, borderRadius: 8, alignItems: 'center', minHeight: 48 },
    secondaryBtn: { backgroundColor: theme.surface, padding: 12, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: theme.cardBorder, minHeight: 48 },
    primaryBtnSmall: { backgroundColor: theme.primary, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center', minHeight: 48 },
    secondaryBtnSmall: { backgroundColor: theme.surface, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, alignItems: 'center', borderWidth: 1, borderColor: theme.cardBorder, minHeight: 48 },
    secondaryBtnText: { color: theme.text, fontWeight: '600' },
    btnTxt: { fontWeight: '800', color: theme.onAccent, letterSpacing: 1 },
    
    // Vault
    docRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: theme.card, padding: 16, borderRadius: 8, marginBottom: 12, borderWidth: 1, borderColor: theme.cardBorder },
    docIcon: { width: 40, height: 40, borderRadius: 8, alignItems: 'center', justifyContent: 'center', marginRight: 16 },
    docTitle: { color: theme.text, fontWeight: '600', fontSize: 16 },
    docSub: { color: theme.textDim, fontSize: 14, fontFamily: Fonts.mono },
    dashedBtn: { borderWidth: 1, borderColor: theme.cardBorder, borderStyle: 'dashed', borderRadius: 8, padding: 16, alignItems: 'center', marginTop: 10 },

    // Config
    pageTitle: { fontSize: 28, fontWeight: '700', color: theme.text, marginBottom: 4 },
    pageTitleSmall: { fontSize: 18, fontWeight: '700', color: theme.text },
    pageSub: { color: theme.textDim, marginBottom: 0, fontSize: 12, paddingLeft: 2 },
    pageHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
    stickyHeader: { position: 'absolute', left: 0, right: 0, top: 0, zIndex: 10, backgroundColor: theme.bg, borderBottomWidth: 1, borderBottomColor: theme.cardBorder },
    stickyHeaderInner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 12 },
    headerIconBtn: { width: 48, height: 48, borderRadius: 8, backgroundColor: theme.primary, alignItems: 'center', justifyContent: 'center', shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 6, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
    headerIconBtnGhost: { width: 48, height: 48, borderRadius: 8, backgroundColor: theme.card, borderWidth: 1, borderColor: theme.cardBorder, alignItems: 'center', justifyContent: 'center' },
    settingsHeader: { color: theme.textDim, fontSize: 14, fontWeight: '600', marginTop: 16, marginBottom: 8, paddingHorizontal: 2, textTransform: 'uppercase', letterSpacing: 0.4 },
    settingsGroup: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, overflow: 'hidden', marginBottom: 12 },
    settingsRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, minHeight: 48 },
    settingsDivider: { height: 1, backgroundColor: theme.cardBorder },
    settingsLabel: { color: theme.text, fontSize: 16 },
    settingsValue: { color: theme.textDim, fontSize: 16 },
    settingsDestructive: { color: theme.danger, fontSize: 16, fontWeight: '600' },
    settingsChoiceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, minHeight: 48 },
    settingsChoiceLabel: { color: theme.text, fontSize: 16 },

    // Modals
    modalBase: { flex: 1, paddingTop: 60 },
    modalHeader: { paddingHorizontal: 20, paddingBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    modalH1: { fontSize: 20, fontWeight: '700', color: theme.text },
    modalSaveText: { color: theme.primary, fontWeight: '600', fontSize: 16 },
    modalCancelText: { color: theme.primary, fontWeight: '600', fontSize: 16 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', padding: 40 },
    modalPopup: { backgroundColor: theme.card, padding: 24, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder },
    popupTitle: { color: theme.text, fontSize: 18, fontWeight: '600', marginBottom: 16 },
    popupHelp: { color: theme.textDim, fontSize: 14, marginTop: 6 },
    popupBtn: { flex: 1, padding: 12, borderRadius: 8, alignItems: 'center', minHeight: 48 },
    addLogOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: theme.bg, zIndex: 20 },
    logForm: { padding: 20, paddingBottom: 40 },
    formSection: { marginBottom: 18 },
    sectionHeader: { color: theme.textDim, fontSize: 14, fontWeight: '600', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.4 },
    listGroup: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, overflow: 'hidden' },
    listRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 16 },
    listLabel: { color: theme.text, fontSize: 15, fontWeight: '500', minWidth: 110, flexShrink: 0 },
    listValue: { color: theme.text, fontSize: 16, textAlign: 'right' },
    listValueRow: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 6 },
    listInput: { flex: 1, textAlign: 'right', color: theme.text, fontSize: 16 },
    typeRow: { flex: 1, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 8 },
    typePill: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: theme.surface },
    typePillActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    typePillText: { color: theme.textDim, fontSize: 14, fontWeight: '600' },
    typePillTextActive: { color: 'white' },
    typeSelectBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingRight: 12 },
    typeNameRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
    typeName: { color: theme.text, fontSize: 15, fontWeight: '500' },
    swipeDelete: { width: 64, backgroundColor: theme.danger, alignItems: 'center', justifyContent: 'center' },
    listDivider: { height: 1, backgroundColor: theme.cardBorder },
    notesInput: { minHeight: 120, paddingHorizontal: 14, paddingVertical: 12, color: theme.text, fontSize: 15, textAlignVertical: 'top' },
    datePickerRow: { paddingHorizontal: 12, paddingBottom: 8, backgroundColor: theme.card },
    formFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 16, backgroundColor: theme.bg, borderTopWidth: 1, borderTopColor: theme.cardBorder, flexDirection: 'row', gap: 12 },

    // Industrial additions
    plateWrap: { flexDirection: 'row', alignItems: 'center', width: '100%', borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: '#FFFFFF', borderRadius: 8, overflow: 'hidden' },
    plateStrip: { width: 38, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1E40AF', height: 56 },
    plateStripText: { color: 'white', fontWeight: '800', fontSize: 16, fontFamily: Fonts.mono },
    plateInput: { flex: 1, height: 56, paddingHorizontal: 14, fontFamily: Fonts.mono, fontSize: 18, color: '#0F172A', letterSpacing: 2 },

    specSheet: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginHorizontal: 20, marginBottom: 16 },
    specRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    specMake: { fontSize: 20, fontWeight: '800', color: theme.text, textTransform: 'uppercase' },
    specNickname: { fontSize: 18, fontWeight: '700', color: theme.textDim, marginTop: 2 },
    specModel: { fontSize: 28, fontWeight: '800', color: theme.text, fontFamily: Fonts.sans },
    specLogo: { width: 60, height: 60, alignItems: 'center', justifyContent: 'center' },
    specPlateBox: { marginTop: 12, borderWidth: 1, borderColor: theme.cardBorder, borderRadius: 8, paddingVertical: 12, alignItems: 'center', backgroundColor: theme.surface },
    specPlateText: { fontFamily: Fonts.mono, fontSize: 22, color: theme.text, letterSpacing: 3 },
    vinRow: { marginTop: 10 },
    vinLabel: { fontSize: 12, color: theme.textDim, fontWeight: '700', textTransform: 'uppercase' },
    vinValue: { fontFamily: Fonts.mono, fontSize: 14, color: theme.text },

    statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, paddingHorizontal: 20 },
    statusTile: { width: '48%', backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 12, minHeight: 96 },
    statusTileAction: { backgroundColor: theme.primary, borderColor: theme.primary, borderRadius: 12 },
    statusTileHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    statusTileLabel: { fontSize: 14, fontWeight: '700', color: theme.textDim, textTransform: 'uppercase' },
    statusTileValue: { fontSize: 18, fontWeight: '800', color: theme.text, fontFamily: Fonts.mono },
    statusTileSub: { fontSize: 14, color: theme.textDim, marginTop: 4 },

    timelineRow: { flexDirection: 'row', gap: 16, paddingHorizontal: 20, paddingBottom: 18 },
    timelineLine: { position: 'absolute', left: 44, top: 0, bottom: 0, width: 2, backgroundColor: theme.cardBorder, opacity: 0.3 },
    timelineDate: { width: 56, alignItems: 'center', paddingRight: 8 },
    timelineDay: { fontFamily: Fonts.mono, fontSize: 22, fontWeight: '800', color: theme.text },
    timelineMonth: { fontFamily: Fonts.mono, fontSize: 14, fontWeight: '700', color: theme.textDim },
    timelineCard: { flex: 1, backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 12 },
    timelineHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
    timelineTitle: { fontSize: 16, fontWeight: '700', color: theme.text, flexShrink: 1 },
    timelineMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
    timelineMeta: { fontFamily: Fonts.mono, fontSize: 14, color: theme.textDim },

    typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    typeButton: { width: '30%', minHeight: 72, borderWidth: 1, borderColor: theme.cardBorder, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: theme.surface, paddingHorizontal: 6 },
    typeButtonActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    typeButtonText: { marginTop: 6, fontSize: 12, fontWeight: '700', color: theme.textDim, textTransform: 'uppercase', textAlign: 'center', lineHeight: 14 },
    typeButtonTextActive: { color: theme.onAccent },

    quickAddRow: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 16, flexWrap: 'wrap', justifyContent: 'center' },
    quickAddBtn: { minWidth: 64, borderWidth: 1, borderColor: theme.cardBorder, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 8, alignItems: 'center', backgroundColor: theme.surface },
    quickAddText: { fontSize: 12, fontWeight: '700', color: theme.text },
    quickAddBtnPositive: { borderColor: theme.success, backgroundColor: 'rgba(34,197,94,0.12)' },
    quickAddBtnNegative: { borderColor: theme.danger, backgroundColor: 'rgba(239,68,68,0.12)' },
    quickAddTextPositive: { color: theme.success },
    quickAddTextNegative: { color: theme.danger },

    docAddBtn: { backgroundColor: theme.primary, borderRadius: 8, paddingVertical: 14, paddingHorizontal: 16, minHeight: 48, alignItems: 'center' },
    docAddBtnText: { fontSize: 16, fontWeight: '800', color: theme.onAccent, letterSpacing: 1 },
    docTypeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
    docTypeChip: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: theme.surface },
    docTypeChipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    docTypeChipText: { color: theme.text, fontWeight: '600', fontSize: 14 },
    docTypeChipTextActive: { color: theme.onAccent, fontWeight: '700' },
    docViewerCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16 },
    docViewerTitle: { color: theme.text, fontSize: 18, fontWeight: '700', marginBottom: 8 },
    docViewerNote: { color: theme.text, fontSize: 16 },
    copyMenu: { position: 'absolute', paddingVertical: 6, paddingHorizontal: 12, backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, elevation: 6 },
    copyMenuText: { color: theme.text, fontSize: 14, fontWeight: '700' },

    scrapBtn: { borderWidth: 1, borderColor: theme.danger, borderRadius: 8, paddingVertical: 14, alignItems: 'center', backgroundColor: 'transparent' },
    scrapBtnText: { color: theme.danger, fontWeight: '800', fontSize: 16, letterSpacing: 1 },

    folderCard: { backgroundColor: theme.card, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, padding: 16, marginBottom: 16, position: 'relative' },
    folderTab: { position: 'absolute', top: -10, left: 14, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8, borderWidth: 1, borderColor: theme.cardBorder, backgroundColor: theme.surface },
    folderTabText: { fontSize: 14, fontWeight: '700', color: theme.textDim, textTransform: 'uppercase' },
  });
